### ISSUE TITLE
M0 doesn't work for me

### ISSUE THREAD

**Issue by IohannesArnold** [oriansj/stage0#11]
I'm using musl-based, x86_64 VoidLinux, and compiled `hex` and `vm` to produce `stage0_monitor`, `stage1_assembler-0`, `stage1_assembler-1`, `stage1_assembler-2`, and `M0` all with the correct SHA256 sums. But then I run into this problem:
```
cat ../stage0/High_level_prototypes/defs ../stage0/stage2/lisp.s > lisp.S
./vm --rom ./M0 --tape_01 ./lisp.S --tape_02 lisp.hex2 --memory 1M
```
yields
```
Invalid instruction was recieved at address:00000052
After 207093 instructions
Unable to execute the following instruction:
        31100100
```

No experience at all in assembly or any low-level programming, so I'm not sure if I'm doing something wrong or if it's a bug. Though if you're willing to guide me I'm happy to explore. Really impressed by this project, so I hope this is helpful.

**Comment by IohannesArnold** [comment]
On further investigation, while my M0 rom has the right hash (`3020b...abbdca`) I can seem to use it to correctly compile any of the .s files.

**Comment by Pixeliz3d** [comment]
amd64 Gentoo Hardened
I can also reproduce this issue. M0 always crashes, with this error: `Invalid instruction was recieved at address:00000052`. None of these files can be compiled: lisp.s forth.s cc_x86.s

sha256 hash for M0 is correct (3020b194ead31ae19ba66fc35ed95465514373f6005896350d1608c9efabbdca).

M0 output, when compiling lisp.s:
```
Invalid instruction was recieved at address:00000052
After 207093 instructions
Unable to execute the following instruction:
        31100100
```

forth.s:
```
Invalid instruction was recieved at address:00000052
After 232370 instructions
Unable to execute the following instruction:
        50534B49
```

cc_x86.s:
```
Invalid HALCODE
Computer Program has Halted
Invalid instruction was recieved at address:00000052
After 206237 instructions
Unable to execute the following instruction:
        42000000
```

**Comment by Pixeliz3d** [comment]
If you will try compile M0-macro.s after compiling M0-macro.hex2, it will compile, but files from stage2 still didn't. Now they are giving this error:

```
Invalid instruction was recieved at address:00000000
After 1 instructions
Unable to execute the following instruction:
        15EFC100
```

**Comment by oriansj** [comment]
@IohannesArnold thank you for taking the time to create an issue (sorry for the delay in response)
If the checksums match, the behavior by mathematical definition must be identical. Thus the hardware (the vm in this case) must be at fault.

I attempted to replicate your issue by creating a blank system via the following steps:
qemu-img create prototype.qcow2 20G -f qcow2
qemu-system-x86_64 -m 1024 -smp 1 -boot menu=on -enable-kvm -drive file=prototype.qcow2 -drive file=void-live-x86_64-musl-20181111.iso
*everything defaults via void-installer then reboot*
sudo xbps-install -S
sudo xbps-install -S git tig gcc make
git clone 'https://github.com/oriansj/stage0'
cd stage0
make clean test

and M0 does not demonstrate the issue you are reporting; unless you are mistaking the hex2 output of M0 as a directly runnable binary (which it is not) as the output of M0 needs to be processed by hex2 to generate a valid binary (as you would see in the output of make test as it builds everything).

If git pull, followed by make clean test doesn't resolve your issue; then the troubleshooting process would be attempting to figure out how musl differs from glibc's behavior in regards to the vm's C source code (The likely problem points are division and treatment of large ints).

**Comment by oriansj** [comment]
@Pixeliz3d I've been using install-amd64-minimal-20190403T214503Z.iso and used eselect profile set 14 to setup hardened (stable). However after emerge dev-vcs/git tig gcc make I am unable to reproduce your issue. Could you please provide additional system information, such that I would be able to completely reproduce the environment to help you further isolate the issue?
