### ISSUE TITLE
stage0 and the c++ abomination

### ISSUE THREAD

**Issue by sylware** [oriansj/stage0#37]
More and more ppl are starting to realize that we needed "stage0s" and alternative C (I mean C89 with benign bits of c99/c11) compilers... but the fact that g++ switched to c++98 instead of being implemented in a simple dialect of C is probably one of the biggest mistakes in software, ever. Instead of having only a few steps to bootstrap the gcc compilers, you will need 1 billion steps in order to reach a recent enough gcc to fit the tantrums of many recent pieces of software:
From the canonical gcc 4.7.4, how many gccs I have to compile to reach 11.2?

**Comment by sylware** [comment]
I was able to compile a minimal gcc 10.3.0 to generate x86 machine code with g++ 4.7.4.

**Comment by oriansj** [comment]
Well it takes 100 steps to reach even GCC 4.7.4 https://github.com/fosslinux/live-bootstrap/blob/master/parts.rst
but to go from GCC 4.7.4 to the latest GCC is only 2 GCC steps
